version: '{build}'
os: Visual Studio 2019
configuration: Debug
build: off
test: off
deploy: off

environment:
  global:
    OS: "windows"
    ARCH: "x86"
    CC: "ccache gcc"
    CXX: "ccache g++"
    MINGW: C:/Qt/Tools/mingw730_32
    QTDIR: C:/Qt/5.14/mingw73_32
    QTIFWDIR: C:/Qt/Tools/QtInstallerFramework/3.2
    VCRT_DIR: 'C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/Redist/x86/Microsoft.VC140.CRT'
    DEPLOY_INSTALLER: true

cache:
  - C:/msys64/home/appveyor/.ccache

init:
  - set PATH=%QTDIR%/bin;%MINGW%/bin;C:/Qt/Tools/QtCreator/bin;%QTIFWDIR%/bin;C:/msys64/bin;C:/msys64/usr/bin;C:/msys64/mingw64/bin;%PATH%

install:
  - git submodule update --init --recursive
  - bash -c "./ci/install_dependencies.sh"

build_script:
  - bash -c "./ci/stylecheck.sh"
  - bash -c "./ci/build_librepcb.sh"
  - bash -c "./ci/build_windows_archive.sh"
  - bash -c "./ci/build_installer.sh"
  - build\output\qztest.exe
  - build\output\librepcb-unittests.exe
  - pytest -v --librepcb-executable="build/install/opt/bin/librepcb-cli.exe" tests/cli
  - pytest -v --librepcb-executable="build/install/opt/bin/librepcb.exe" tests/funq
  - bash -c "./ci/upload_artifacts.sh"
